import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FooterComponent } from "@/src/components/ui/footer";
import HeaderComponent from "@/src/components/ui/header";
import Providers from "./providers";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/src/i18n/routing";
import { getMessages, setRequestLocale } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Architect",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};

export default async function LocaleLayout({ children,params}: Props){

  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages=await getMessages();
  setRequestLocale(locale);
  return (
    <html lang="en">
      <body
       style={{direction :locale=="ar" ? "rtl":"ltr"}}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <NextIntlClientProvider locale={locale}  messages={messages}>
        <HeaderComponent/>
        <Providers >
          <div className="content-wrapper min-h-screen">
            {children}
          </div>
        </Providers>
        <FooterComponent/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
